// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGVaOEYBe7l_e0LXiqO6f-hlL4VSauIVo',
    appId: '1:873924788444:web:339ce4ca95c4b2fe20f419',
    messagingSenderId: '873924788444',
    projectId: 'ticketbookingapp-41157',
    authDomain: 'ticketbookingapp-41157.firebaseapp.com',
    storageBucket: 'ticketbookingapp-41157.firebasestorage.app',
    measurementId: 'G-30BD8750Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpORi3jWgXEmVQ4c4KWeA9kAQiGDEXQlo',
    appId: '1:873924788444:android:3cdb6c2e8306352120f419',
    messagingSenderId: '873924788444',
    projectId: 'ticketbookingapp-41157',
    storageBucket: 'ticketbookingapp-41157.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADXuIAVTQ2Tq0os8mP7iGOLZ9FvXhO1Wg',
    appId: '1:873924788444:ios:73d905e3c9f706ff20f419',
    messagingSenderId: '873924788444',
    projectId: 'ticketbookingapp-41157',
    storageBucket: 'ticketbookingapp-41157.firebasestorage.app',
    iosBundleId: 'com.example.yourTickets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADXuIAVTQ2Tq0os8mP7iGOLZ9FvXhO1Wg',
    appId: '1:873924788444:ios:73d905e3c9f706ff20f419',
    messagingSenderId: '873924788444',
    projectId: 'ticketbookingapp-41157',
    storageBucket: 'ticketbookingapp-41157.firebasestorage.app',
    iosBundleId: 'com.example.yourTickets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGVaOEYBe7l_e0LXiqO6f-hlL4VSauIVo',
    appId: '1:873924788444:web:7a40dd1357e1024920f419',
    messagingSenderId: '873924788444',
    projectId: 'ticketbookingapp-41157',
    authDomain: 'ticketbookingapp-41157.firebaseapp.com',
    storageBucket: 'ticketbookingapp-41157.firebasestorage.app',
    measurementId: 'G-EJZ1WTBMTH',
  );
}
